name: Python CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install system dependencies for manimpango
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libcairo2-dev \
            libpango1.0-dev

      - name: Upgrade pip and install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build project and install dependencies
        run: |
          python -m build
          pip install .